#region (c)2009 Lokad - New BSD license

// Copyright (c) Lokad 2009 
// Company: http://www.lokad.com
// This code is released under the terms of the new BSD licence

#endregion

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

namespace Lokad.Diagnostics.Persist
{
	/// <summary>
	/// Diagnostics: Persistence class for aggregated exception info.
	/// </summary>
	[Serializable]
	[DebuggerDisplay("{Name}: {Count}")]
	public sealed class ExceptionData
	{
		/// <summary>
		/// Unique exception ID, as logged on the system
		/// </summary>
		/// <value>The ID.</value>
		[XmlAttribute]
		public Guid ID { get; set; }

		/// <summary>
		/// Gets or sets name of the exception
		/// </summary>
		/// <value>Name of the exception.</value>
		[XmlAttribute]
		public string Name { get; set; }

		/// <summary>
		/// Gets or sets message associated with the exception
		/// </summary>
		/// <value>Message associated with the exception.</value>
		public string Message { get; set; }

		/// <summary>
		/// Gets or sets full textual representation, as generated by ToString()
		/// </summary>
		/// <value>Full textual representation, as generated by ToString.</value>
		public string Text { get; set; }

		/// <summary>
		/// Gets or sets the number of times this exception has occurred.
		/// </summary>
		/// <value>The number of times this exception has occurred.</value>
		[XmlAttribute, DefaultValue(0)]
		public long Count { get; set; }
	}
}